### ISSUE TITLE
I2CDevice.cpp missing definitions 

### ISSUE THREAD

**Issue by usmanmehmood55** [loopj/i2c-hal#21]
In I2CDevice.cpp, there is no definitions of `readBytes()` and `writeBytes()`
So it gives these errors while compiling
```
undefined reference to `I2CDevice::readBytes(unsigned char, unsigned char, unsigned char*)'
undefined reference to `I2CDevice::writeBytes(unsigned char, unsigned char, unsigned char*)'
```
I'm using Segger Embedded Studio and compiling your code for nRF52-DK 
Please help,

**Comment by loopj** [comment]
`I2CDevice::readBytes` and `I2CDevice::writeBytes` are defined in the implementation files for the supported platforms:

I2CDevice_arduino.cpp
I2CDevice_mbed.cpp
I2CDevice_wiringpi.cpp

**Comment by usmanmehmood55** [comment]
Thank you so much for the answer. 
Could you please tell me how I could use (include) I2CDevice_mbed.cpp in my code? There is an `#ifdef  __MBED__` statement in it, so I would have to define it in main.cpp before calling the library, right? 
I just want to know what exactly I have to define? 

I understand that I would have to modify these functions in I2CDevice_mbed.cpp to communicate with nRF52 SDK's own TWI APIs.
